### ISSUE TITLE
Generates new key at every startup

### ISSUE THREAD

**Issue by Derkades** [crocandr/docker-tinc#8]
After syncing hosts I need to restart the container to load the new hosts, but when restarting it creates a new private key for itself:
```
tinc_1  | STARTED: Tue 17 Nov 2020 11:58:29 AM CET
tinc_1  | Generating 4096 bits keys:
tinc_1  | .......................................++++ p
tinc_1  | ........................................++++ q
tinc_1  | Done.
tinc_1  | Warning: old key(s) found and disabled.
```
This creates an loop scenario that makes it impossible to use this image.

It appears the entrypoint script does [attempt to check if a key already exists](https://github.com/crocandr/docker-tinc/blob/master/files/start.sh#L65), but it generates a new key regardless.

docker-compose:
```yaml
  tinc:
    image: croc/tinc
    ports:
      - 26488:26488/tcp
      - 26488:26488/udp
    environment:
      - SITENAME=test
      - PORT=26488
      - PUBADDR=mydomain
      - LANIP=10.131.1.253/24
      - SUBNET=10.131.1.0/24
    volumes:
      - './tinc:/etc/tinc/site2site/hosts'
      - '/etc/localtime:/etc/localtime:ro'
    cap_add: ['net_admin']
    devices: ['/dev/net/tun:/dev/net/tun']
    restart: always
```
